"""Standalone HTML report with embedded CSS and sortable table."""

from vulnscope.models import ScanResult, Severity

SEVERITY_COLORS = {
    Severity.CRITICAL: "#dc2626",
    Severity.HIGH: "#ea580c",
    Severity.MEDIUM: "#ca8a04",
    Severity.LOW: "#0891b2",
    Severity.UNKNOWN: "#6b7280",
}


def to_html(result: ScanResult) -> str:
    os_info = result.os_info
    counts = result.counts_by_severity
    vulns = result.vulnerabilities

    rows_html = ""
    for v in vulns:
        color = SEVERITY_COLORS.get(v.severity, "#6b7280")
        kev = "⚠" if v.is_known_exploited else ""
        cvss = f"{v.cvss_score:.1f}" if v.cvss_score is not None else "N/A"
        fixed = v.fixed_version or "—"
        ref_links = " ".join(
            f'<a href="{r}" target="_blank" rel="noopener">[ref]</a>'
            for r in v.references[:3]
        )
        rows_html += f"""
        <tr>
          <td><a href="https://nvd.nist.gov/vuln/detail/{v.cve_id}" target="_blank" rel="noopener">{v.cve_id}</a></td>
          <td>{v.affected_package.name}</td>
          <td>{v.affected_package.version}</td>
          <td>{fixed}</td>
          <td><span class="badge" style="background:{color}">{v.severity.value.upper()}</span></td>
          <td>{cvss}</td>
          <td style="color:#dc2626;font-weight:bold">{kev}</td>
          <td style="font-size:0.85em">{ref_links}</td>
        </tr>"""

    severity_badges = ""
    for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
        count = counts.get(sev, 0)
        if count:
            color = SEVERITY_COLORS[sev]
            severity_badges += f'<span class="badge" style="background:{color}">{sev.value.upper()}: {count}</span> '

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VulnScope Scan Report</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }}
    h1 {{ color: #60a5fa; font-size: 1.8rem; margin-bottom: 0.5rem; }}
    .meta {{ color: #94a3b8; margin-bottom: 1.5rem; font-size: 0.9rem; }}
    .summary {{ display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; align-items: center; }}
    .badge {{ display: inline-block; padding: 0.25rem 0.6rem; border-radius: 4px; color: white; font-weight: bold; font-size: 0.85rem; }}
    .risk {{ background: #1e293b; padding: 0.5rem 1rem; border-radius: 6px; color: #94a3b8; }}
    table {{ width: 100%; border-collapse: collapse; background: #1e293b; border-radius: 8px; overflow: hidden; }}
    th {{ background: #0f172a; padding: 0.75rem 1rem; text-align: left; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; color: #94a3b8; cursor: pointer; user-select: none; }}
    th:hover {{ color: #60a5fa; }}
    td {{ padding: 0.6rem 1rem; border-bottom: 1px solid #0f172a; font-size: 0.9rem; vertical-align: middle; }}
    tr:hover td {{ background: #162032; }}
    a {{ color: #60a5fa; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .footer {{ margin-top: 2rem; color: #475569; font-size: 0.8rem; text-align: center; }}
  </style>
</head>
<body>
  <h1>VulnScope Scan Report</h1>
  <div class="meta">
    {os_info.get('pretty_name', 'Linux')} &nbsp;|&nbsp;
    Kernel: {os_info.get('kernel_version', '?')} &nbsp;|&nbsp;
    Scanned {result.total_packages} packages &nbsp;|&nbsp;
    {result.scan_duration_seconds:.1f}s &nbsp;|&nbsp;
    {result.timestamp}
  </div>
  <div class="summary">
    {severity_badges}
    <span class="risk">Risk Score: <strong>{result.risk_score}/100</strong></span>
  </div>
  <table id="vuln-table">
    <thead>
      <tr>
        <th onclick="sortTable(0)">CVE ID</th>
        <th onclick="sortTable(1)">Package</th>
        <th onclick="sortTable(2)">Installed</th>
        <th onclick="sortTable(3)">Fixed</th>
        <th onclick="sortTable(4)">Severity</th>
        <th onclick="sortTable(5)">CVSS</th>
        <th onclick="sortTable(6)">KEV</th>
        <th>Refs</th>
      </tr>
    </thead>
    <tbody>
      {rows_html}
    </tbody>
  </table>
  <div class="footer">Generated by <a href="https://github.com/michaelsc44/vulnscope">VulnScope</a></div>
  <script>
    function sortTable(col) {{
      const table = document.getElementById('vuln-table');
      const tbody = table.querySelector('tbody');
      const rows = Array.from(tbody.querySelectorAll('tr'));
      const dir = table.getAttribute('data-sort-dir') === 'asc' ? -1 : 1;
      rows.sort((a, b) => {{
        const ca = a.cells[col].textContent.trim();
        const cb = b.cells[col].textContent.trim();
        const na = parseFloat(ca), nb = parseFloat(cb);
        if (!isNaN(na) && !isNaN(nb)) return dir * (na - nb);
        return dir * ca.localeCompare(cb);
      }});
      table.setAttribute('data-sort-dir', dir === 1 ? 'asc' : 'desc');
      rows.forEach(r => tbody.appendChild(r));
    }}
  </script>
</body>
</html>"""
